### ISSUE TITLE
Hlasmplugin Language Server crashes on ARM64/aarch64 linux

### ISSUE THREAD

**Issue by josefwegner** [eclipse-che4z/che-che4z-lsp-for-hlasm#283]
**Describe the bug**
Starting Visual Studio Code with HLASM Language Support plugin throws errors that Hlasmplugin Language Server could not be started 

**To Reproduce**
1. Install HLASM Language Support v1.9.0
2. Restart Code

**Expected behavior**
HLASM Language Support works

**Screenshots**
![2023-08-25-185257_1920x1080_scrot](https://github.com/eclipse-che4z/che-che4z-lsp-for-hlasm/assets/80200012/074a3e30-7178-43a6-9a3c-6d5091a94286)

**Platform**
 - Editor: VS Code/Theia 1.8.1:
 Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Datum: 2023-08-09T22:39:55.053Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Betriebssystem: Linux arm64 6.1.38-v8+
 - OS: Raspberry Pi OS (Debian Bullseye) AARCH64/ARM64
 - Plugin version: v1.9.0

**Additional context**
The executable in `~/.vscode/extensions/broadcommfd.hlasm-language-support-1.9.0/bin/linux` seems to be AMD64, not ARM64:
```
$ readelf -a language_server
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
...
```

**Comment by slavek-kucera** [comment]
Hello @josefwegner, arm64 is currently only supported via the platform agnostic webassembly server version - please change the extension setting `hlasm.serverVariant` to `wasm` and restart the vscode.

**Comment by josefwegner** [comment]
Hi @slavek-kucera,

Thank you very much, changing the extension settings worked. It would be great if you could add this to the README.md for future ARM users.

**Comment by slavek-kucera** [comment]
@josefwegner The version 1.13.0 now contains native arm64 binary.
